packages:
  - '.'

engineStrict: true

minimumReleaseAge: 4320 # 3 days

strictDepBuilds: true

allowBuilds: {}

blockExoticSubdeps: true

verifyDepsBeforeRun: false
minimumReleaseAgeExclude:
  # Renovate security update: undici@6.28.0
  - undici@6.28.0
